print("My name is Levente.")
lastname = input("Enter your firstname:")
firstname = input("Enter your lastname:")
age = input("Enter your age:")
print(f"Hello, {lastname} {firstname}! Your age is {age}.")